apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: jupyterhub-idle-culler
spec:
  selector:
    app: jupyterhub-idle-culler
  replicas: 1
  template:
    metadata:
      labels:
        app: jupyterhub-idle-culler
    spec:
      containers:
        - name: jupyterhub-idle-culler
          image: quay.io/odh-jupyterhub/jupyterhub-idle-culler:latest
          env:
            - name: JUPYTERHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: jupyterhub-api-token
                  key: token
          command:
            - jupyterhub-idle-culler
            - --timeout=259200  # 3 days
            - --url=jupyterhub:8080/hub/api
  triggers:
    - type: ConfigChange
